---
always_allow_html: yes
author: "Amol | Haojun | Japneet | Calum"
output:
  html_document: default
  pdf_document: default
pagetitle: Road Safety
---

<style type="text/css">
  body{ /* Normal  */
      font-size: 12px;
  }
.column-left{
  float: left;
  width: 40%;
  text-align: left;
}
.column-right{
  float: right;
  width: 60%;
  text-align: right;
}
/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}
.column-left1{
  float: left;
  width: 80%;
  text-align: left;
}
.column-right1{
  float: right;
  width: 20%;
  text-align: right;
  padding-left: 15px;
  padding-top: 15px;
}
.column-left2{
  float: left;
  width: 47.5%;
  text-align: left;
}
.column-right2{
  float: right;
  width: 47.5%;
  text-align: right;
}
</style>

{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## Install and library necessary libraries

packages <- c("plotly", "tidyverse", "ggmap", "GGally", "gridExtra", "scales", "viridis", "scatterplot3d", "readxl")
newPackages <- packages[!(packages %in% installed.packages()[,"Package"])]
if(length(newPackages)) install.packages(newPackages)
library(tidyverse)
library(plotly)
library(gridExtra)
library(scales)
library(GGally)
library(viridis)
library(ggmap)
library(scatterplot3d)
library(readxl)

# Load necessary data files

load("passfail.RData")
load("nct_geom.RData")

# Private API key for google maps. Please do not share.

register_google("AIzaSyDy7z18GxhakN5ACVLsdqQfIm5B9jRmXpA")


## NCT Statistics Report {.tabset}

### Pass/Fail overview - Calum

{r,echo=FALSE}

# Data preparation

passfailtotals <- summarise(group_by(passfail,Year),Pass1=sum(Pass1),Fail1=sum(Fail1),Total1=sum(Total1),Pass2=sum(Pass2),Fail2=sum(Fail2),Total2=sum(Total2))
passfailtotals <- mutate(passfailtotals,Pass1prop=Pass1/Total1,Pass2prop=Pass2/Total2)[c(1,2,3,4,8,5,6,7,9)]
passfailtotals1 <- passfailtotals[c(1,2,3,4)]
names(passfailtotals1) <- c("Year","Pass","Fail","Total")
passfailtotals1$Test <- "First"
passfailtotals2 <- passfailtotals[c(1,6,7,8)]
names(passfailtotals2) <- c("Year","Pass","Fail","Total")
passfailtotals2$Test <- "Retest"
passfailtotals0 <- rbind(passfailtotals1,passfailtotals2)
passfailtotals1 <- passfailtotals0[c(1,2,4,5)]
names(passfailtotals1) <- c("Year","Count","Total","Test")
passfailtotals1$Result <- "Pass"
passfailtotals2 <- passfailtotals0[c(1,3,4,5)]
names(passfailtotals2) <- c("Year","Count","Total","Test")
passfailtotals2$Result <- "Fail"
passfailtotals0 <- rbind(passfailtotals1,passfailtotals2)
passfailtotals0$Result<-factor(passfailtotals0$Result,c("Pass","Fail"))
passfailtotals0$Test<-factor(passfailtotals0$Test,c("First","Retest"))


Let us begin with an overview of the data. The NCT is a test that all cars over 4 years of age must undergo to legally drive on roads in Ireland. We have NCT pass and fail data for almost 12 million cars tested from 2013 to 2018. This data was recorded from all 47 test centres scattered across Ireland. This includes both initial test and retest data. Please note retest data was not available for 2014, hence it was omitted from our report. Here's an overview of how this data is distributed.

```{r,echo=FALSE, warning=FALSE,fig.width=9, fig.height=2.5}

# Pass/Fail count barplot

p1 <- ggplot(passfailtotals0,aes(x=Year,y=Count, fill=Result))+
  geom_col(position="dodge")+
  theme_bw()+
  theme(legend.position = "none",legend.title = element_blank())+
  scale_fill_manual(values = c("lightblue","slategray"))+
  facet_wrap(~Test)+
  scale_y_continuous(labels = comma)

# Pass/Fail rate barplot

p2 <- ggplot(passfailtotals0,aes(x=Year,y=Count, fill=Result))+
  geom_col(position="fill")+
  labs(y="Proportion")+
  geom_hline(yintercept = 0.5,col="red")+
  theme_bw()+
  theme(legend.key = element_rect(colour="black"), legend.position = c(0.912,0.85),legend.title = element_blank(), legend.background = element_rect(fill="transparent"), legend.text = element_text(size = 8))+
  scale_fill_manual(values = c("lightblue","slategray"))+
  facet_wrap(~Test)

# Arrange plots side by side